brew install \
    aom \
    argocd \
    aribb24 \
    bazel \
    brotli \
    ca-certificates \
    cairo \
    cjson \
    dav1d \
    ffmpeg \
    flac \
    fontconfig \
    freetype \
    frei0r \
    fribidi \
    gettext \
    ghostscript \
    giflib \
    glib \
    gmp \
    gnutls \
    graphite2 \
    harfbuzz \
    helm \
    highway \
    icu4c@76 \
    imagemagick \
    imath \
    jasper \
    jbig2dec \
    jpeg-turbo \
    jpeg-xl \
    k9s \
    kind \
    krb5 \
    kubernetes-cli \
    lame \
    leptonica \
    libarchive \
    libass \
    libb2 \
    libbluray \
    libde265 \
    libdeflate \
    libevent \
    libheif \
    libidn \
    libidn2 \
    liblqr \
    libmicrohttpd \
    libnghttp2 \
    libogg \
    libomp \
    libpng \
    libraw \
    librist \
    libsamplerate \
    libsndfile \
    libsodium \
    libsoxr \
    libssh \
    libtasn1 \
    libtiff \
    libtool \
    libunibreak \
    libunistring \
    libvidstab \
    libvmaf \
    libvorbis \
    libvpx \
    libx11 \
    libxau \
    libxcb \
    libxdmcp \
    libxext \
    libxrender \
    little-cms2 \
    lz4 \
    lzo \
    m4 \
    maven \
    mbedtls \
    mpdecimal \
    mpg123 \
    ncurses \
    nettle \
    opencore-amr \
    openexr \
    openjdk \
    openjdk@21 \
    openjpeg \
    openssl@3 \
    opus \
    p11-kit \
    pango \
    pcre \
    pcre2 \
    pixman \
    postgresql@16 \
    python-packaging \
    python@3.13 \
    rav1e \
    readline \
    rubberband \
    sdl2 \
    shared-mime-info \
    snappy \
    speex \
    sqlite \
    srt \
    svt-av1 \
    telepresence-oss \
    telnet \
    tesseract \
    theora \
    tmux \
    unbound \
    utf8proc \
    webp \
    wget \
    x264 \
    x265 \
    xorgproto \
    xvid \
    xz \
    zeromq \
    zimg \
    zsh \
    zstd \

brew install --cask \
    alt-tab \
    bartender \
    breaktimer \
    hiddenbar \
    itsycal \
    kap \
    keka \
    maccy \
    menubar-stats \
    one-switch \
    rectangle \
    soundsource \
    stats \
    sublime-text \
    vlc \
    wifi-explorer \
    xquartz \
    zoom \
